### ISSUE TITLE
Looking for Volunteers

### ISSUE THREAD

**Issue by corey-hammerton** [voxpupuli/pypuppetdb#107]
I regret having to make this request. Due to changing circumstances in my life I will no longer be an active maintainer on this project. I still hope to contribute code but it will be at an infrequent rate. I have greatly enjoyed being a part of this project, helping to push it into the PuppetDB 3.x generation and beyone.

Anyone who wishes to step up please provide the following:
- [ ] Github username
- [ ] Pypi username

As @daenney mentioned in #50 we expect this project to remain in the voxpupuli community since this project was started by members of the Puppet Community and should remain there.

**Comment by mterzo** [comment]
Gonna close this since i'm helping out.  Of course we can always use additional aid.
