### ISSUE TITLE
Requests 2.12.3 causing issues

### ISSUE THREAD

**Issue by ts-mini** [voxpupuli/pypuppetdb#110]
The error:

```
  File "/usr/lib/python2.7/site-packages/pypuppetdb/api.py", line 512, in environments
    return self._query('environments', **kwargs)
  File "/usr/lib/python2.7/site-packages/pypuppetdb/api.py", line 327, in _query
    auth=(self.username, self.password))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
    self.prepare_auth(auth, url)
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 527, in prepare_auth
    r = auth(self)
  File "/usr/lib/python2.7/site-packages/requests/auth.py", line 68, in __call__
    r.headers['Authorization'] = _basic_auth_str(self.username, self.password)
  File "/usr/lib/python2.7/site-packages/requests/auth.py", line 38, in _basic_auth_str
    b64encode(b':'.join((username, password))).strip()

```
forcing a 2.12.1 install works, so does adding a username and password into the connect:

```
db = connect(
        username='username'
        password='password'
        host='puppetdb'
        port=8080)
```

**Comment by steveclark72** [comment]
I have also come across this issue.  Another potential fix is to check that username and password are strings before passing them in the optional auth parameter on the GET and POST methods (around line 322 in api.py).  If either are set to None then don't pass the auth parameter.

Apologies if my Python terminology is a bit garbled, but I'm new to Python.

**Comment by mterzo** [comment]
How are you configuring user/pass authentication?  I just see RBAC in 4.3 and that's Token based.

**Comment by redref** [comment]
The error according to stacktrace -
TypeError: sequence item 0: expected a bytes-like object, NoneType found

**Comment by redref** [comment]
Impacted versions of requests : 2.12.2, 2.12.3
Versions 2.12.1 and 2.12.4 are ok.

**Comment by mterzo** [comment]
Yeah, I get how / why it's broken.  I can't find the docs on how to configure puppetdb to use authentication other than RBAC and token.

**Comment by redref** [comment]
Oh yeah, did not catch your thought the first time.
I looked into jetty configuration options (auth realm), but puppetdb shipped jetty does not consume them. Maybe some people (caring much about security) pushed puppetdb behind a proxy.

**Comment by steveclark72** [comment]
I have tried an fresh installation again this morning and 'pip install puppetboard' is now pulling in requests 2.13.0 which is working OK for me.  I am using the default authentication for PuppetDB with puppetboard.

**Comment by mterzo** [comment]
The default settings is port 8080 and localhost.  I'm not sure where your authentication comes into play.

**Comment by steveclark72** [comment]
For me the authentication wasn't the problem.  I commented on this issue because puppetboard was not working at all when running the 'pip install puppetboard' command last December due to it pulling in requests 2.12.3.  This is now working with requests 2.13.0 so the issue appears to be fixed - at least in the guise that I saw it.
