### ISSUE TITLE
resources() does not work with AST query any longer (worked in 0.1.1)

### ISSUE THREAD

**Issue by stefanandres** [voxpupuli/pypuppetdb#114]
Hi,
we've been upgrading our puppet-3 to puppet-4 (so also the puppetdb).
With the upgrade of pypuppetdb, we do not get proper results any longer with pypuppetdb, even though the same query still works with curl:

This returns the proper results:
```
curl  -k --key /etc/vps/client_key.pem --cert /etc/vps/client_crt.pem -X POST https://puppetdb.foo.net:8081/pdb/query/v4/resources   -H 'Content-Type:application/json' -d '{"query": ["and", ["=", "type", "Class"], ["=", "title", "Php"]]}'
```

This results empty array:
```
from pypuppetdb import connect
db = connect(host='puppetdb.foo.net',port='8081',ssl_cert='/etc/vps/client_crt.pem',ssl_key='/etc/vps/client_key.pem', timeout=10)
for x in db.resources('', query='["and", ["=", "type", "Class"], ["=", "title", "Php"]]'): print x
```

I can reproduce that with 0.3.2 and 0.2.3.

**Comment by daenney** [comment]
Ping @mterzo @corey-hammerton. I tried helping over IRC (they reached out to me first) but from everything that I can see the query being asked to execute through pypuppetdb and the CLI are identical and should yield identical results.

**Comment by mterzo** [comment]
I don't have a class with Php, but I do have Apt.

```
>>> query='["and", ["=", "type", "Class"], ["=", "title", "Apt"]]'
>>> y = db.resources(query=query)
>>> for x in y:
...     print x
... 
Class[Apt]
Class[Apt]
```

I'm not at all familiar with what "used" to work, but in the resources if you specify the first argument, it expects a title, and adds an extra `/` to the URL and breaks the query.

**Comment by stefanandres** [comment]
Ah, yes. That fixes it. Now we have to do db.resources(query) instead of db.resources('', query). Thanks :)

**Comment by mterzo** [comment]
Still need the query= it's not the first Param

**Comment by stefanandres** [comment]
Of course, this is what it actually looks like in our code, too. Thanks again!
