### ISSUE TITLE
Getting this error while trying a basic tutorial

### ISSUE THREAD

**Issue by iamShantanu101** [voxpupuli/pypuppetdb#118]
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypuppetdb import connect
>>> db = connect()
>>> nodes = db.nodes()
>>> for node in nodes:
...     print(node)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pypuppetdb/api.py", line 392, in nodes
    nodes = self._query('nodes', **kwargs)
  File "/usr/lib/python2.7/site-packages/pypuppetdb/api.py", line 329, in _query
    auth=(self.username, self.password))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /pdb/query/v4/nodes (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x2743350>: Failed to establish a new connection: [Errno 111] Connection refused',)

**Comment by corey-hammerton** [comment]
What host/port is your PuppetDB instance running on?

**Comment by iamShantanu101** [comment]
You mean the server/port defined in puppetdb.conf which is in config directory?

**Comment by corey-hammerton** [comment]
Pypuppetdb by default looks at localhost:8080 for the puppetdb instance. This can be configured through initializing parameters:

`db = connect(host=puppetdb, port=8081)`

There is no configuration file/directory associated with this project.

**Comment by mterzo** [comment]
8081 is the ssl port. You will need to provide your puppetdb certs if you connecting to that port.

**Comment by iamShantanu101** [comment]
Well now it shows 'Name or service not known'. Does this mean there is some issue with PuppetDB configuration?

**Comment by iamShantanu101** [comment]
The hostname has to be FQDN which i'll get using hostname,right? I am using a remote host. Tried with this hostname and port 8081, but still getting connection refused.

**Comment by corey-hammerton** [comment]
What host/port is your PuppetDB instance running? compared to the node your pypuppetdb code is running?

**Comment by iamShantanu101** [comment]
That works now. Maybe it was due to some misconfiguration.
But on trying InOperator(), I got this error:
NameError: name 'InOperator' is not defined

Whereas AndOperator() work fine.
