### ISSUE TITLE
How to query for facts value

### ISSUE THREAD

**Issue by iamShantanu101** [voxpupuli/pypuppetdb#119]
Is there any provision to check whether the fact which is being queried is true?
Ex json output. "name":"httpdrunning","value":"false"
something like this should be evaluated to true/false: 
facts = node.fact('httpdrunning')

**Comment by KlavsKlavsen** [comment]
@iamShantanu101 If you find the solution - remember to update issue with the solution you found - and close the issue. That way if anyone else has the same issue - and find your question - they get helped. Otherwise you're not playing nice.

**Comment by iamShantanu101** [comment]
@KlavsKlavsen Hey, got this working after specifying the desired value alongwith fact name. Closing the issue.
