### ISSUE TITLE
SSLVerify=None & InsecureRequestWarning

### ISSUE THREAD

**Issue by Poil** [voxpupuli/pypuppetdb#128]
Hi,

I think we should hide this warn "InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised" when using SSLVerify=None

Best regards

**Comment by gdubicki** [comment]
Hi @Poil !

I disagree that this should be disabled in the pypuppetdb itself as that warning is valid. Unverified SSL certificate means that you encrypt the communication but forfeit the verification that you are actually talking to the party you want to talk.

But you can easily disable this warning in your code with this:
```
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```
