### ISSUE TITLE
single fact query not returning value

### ISSUE THREAD

**Issue by asagarshinde** [voxpupuli/pypuppetdb#129]
While trying to retrieve particular fact from node it returns the name and node rather than the value and node.

>>> node.fact('ipaddress')
Fact: ipaddress/puppet.server.com
>>> node.fact('operatingsystem')
Fact: operatingsystem/puppet.server.com
>>>

**Comment by internaught** [comment]
Seeing this here too. How are we supposed to get the values from these facts?

**Comment by 6uhrmittag** [comment]
I just found it via trial and error:

You get values like this(here it's the fact `hostname`):

````python

    print("nodes:")
    for node in nodes:
        print(node.fact('hostname').value)
````
