### ISSUE TITLE
Need support for json request body as well as POST

### ISSUE THREAD

**Issue by duskglow** [voxpupuli/pypuppetdb#132]
There does not appear to be support for passing a JSON query string through the request body, even if the POST request_method is selected.  This would be nice functionality, as in our use case the query strings can get VERY big (and have already required us to bump the max query length in puppetdb).

Thanks.

**Comment by kelbyers** [comment]
We have run into an issue with a very large query where PuppetDB responds with an HTTP 414 error, like so:
```HTTPError: 414 Client Error: URI Too Long for url```

If we use the same query that causes this message and specify `request_method='POST'`, then the query is not honored, and results are returned as if we did not specify any query filters. If we modify the code in pypuppetdb to put the query into the body of the request, then then query string is processed by puppetdb, and very long queries are handled.

**Comment by b4ldr** [comment]
can this be closed now !137 is merged?

**Comment by kelbyers** [comment]
> 
> 
> can this be closed now #137 is merged?

Yes, this can be closed. I'm not sure why it wasn't closed earlier, as I thought the text `this closes issue #132` should have automatically taken care of it.
