### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by dwoldenberg1** [voxpupuli/pypuppetdb#141]
Would it be possible to make a new official python release of the package anytime soon?

**Comment by bastelfreak** [comment]
Hey @mterzo, can you look into this?

**Comment by kelbyers** [comment]
Hey, any updates on this?

**Comment by InTheCloudDan** [comment]
I just found this project, wondering if it's still active and worth investing time in using it?

**Comment by westbywest** [comment]
The FromOperator in the most recent commit, in particular, would be pretty integral to typical use cases for subqueries.  New release v3.4 or so would at least get that published to pypi.org.
https://github.com/voxpupuli/pypuppetdb/commit/cedeecf48014b4ad5b8e2513ca8230c814f45603

**Comment by gdubicki** [comment]
Can we get new release please?

**Comment by bastelfreak** [comment]
Hi. I need a review on https://github.com/voxpupuli/pypuppetdb/pull/147. After that got merged, we can do a new release. If one of you feels confident with python, please review that PR.
