### ISSUE TITLE
ssl_verify

### ISSUE THREAD

**Issue by TJM** [voxpupuli/pypuppetdb#143]
While connect's `ssl_verify` *can* be True or False (per the documentation), it can also be the path to a CA Certificate (PEM), or a directory with multiple CA certificates, processed with c_rehash (from OpenSSL). It actually, probably, should default to `/etc/puppetlabs/puppet/certs/ca.pem` rather than "True" ... then the documentation could be updated to no longer indicate the need to mess with the system level CA Trust.

REF: http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification

**Comment by othalla** [comment]
@TJM can you provide the PR regarding the documentation?

**Comment by TJM** [comment]
I am on a different project now, but I will eventually rotate back to that customer. :)

**Comment by b4ldr** [comment]
perhaps we should update the docs to state that it supports a string, however im not sure that we should change the default as the localcacert us distro dependent e.g. on debian its /var/lib/puppet/ssl/certs/ca.pem

**Comment by gdubicki** [comment]
I think that #171 didn't cover everything as we also have info about `ssl_verify` here https://github.com/voxpupuli/pypuppetdb/blame/master/docs/connecting.rst#L50-L63 and there is nothing about being able to pass a path to a CA file there.

So we should also update that piece of docs to resolve this issue.

**Comment by gdubicki** [comment]
This should be fixed by improved docs from https://github.com/voxpupuli/pypuppetdb/pull/201.
