### ISSUE TITLE
Nodes that have errors during runs should not be marked "Unchanged"

### ISSUE THREAD

**Issue by initrd** [voxpupuli/pypuppetdb#161]
Carrying over an issue from [Puppetboard #449](https://github.com/voxpupuli/puppetboard/issues/449) - nodes that show errors during runs are marked as "Unchanged" in Puppetboard. While technically that is correct, it does not reflect their true state. These nodes should show up as "Failed", or under a new label "In error".

Opening this issue for pypuppetdb since [comments](https://github.com/voxpupuli/puppetboard/issues/449#issuecomment-363193385) in the other issue suggest this should be handled upstream here.

Thanks!

**Comment by bastelfreak** [comment]
Hi @initrd, thanks for raising this issue. Are you able to provide a pull request for this?

**Comment by initrd** [comment]
Not at all familiar with the codebase :) Some pointers would help, thank you!

**Comment by b4ldr** [comment]
@initrd i tried to recreate this with the following script however whenever i see an `err` in the logs tags the status is correctly set to 'failed'

```python
#!/usr/bin/env python3
from pypuppetdb import connect
from pypuppetdb.QueryBuilder import AndOperator, EqualsOperator
from os.path import basename

def main():
    found_files = set()
    db = connect()
    query = EqualsOperator('certname', 'mw1359.eqiad.wmnet')
    unchanged_report = db.reports(query=query)
    for report in unchanged_report:
        print(report.status)
        for metric in report.metrics:
            if metric['name'] in ['failed', 'failed_to_restart']:
                print(metric)
        for log in report.logs:
            print(log['tags'])
        print('=' * 80)


if __name__ == '__main__':
    raise SystemExit(main())
```

example output

```
failed
{'name': 'failed', 'value': 0, 'category': 'resources'}
{'name': 'failed_to_restart', 'value': 0, 'category': 'resources'}
['info']
['info']
['info']
['info']
['info']
['err']
['warning']
['err']
```

We could try something like the following but it feel a bit hacky
```
diff --git a/pypuppetdb/types.py b/pypuppetdb/types.py
index 5d75048..ea96b1c 100644
--- a/pypuppetdb/types.py
+++ b/pypuppetdb/types.py
@@ -182,6 +182,11 @@ class Report(object):
         self.transaction = transaction
         self.environment = environment
         self.status = 'noop' if noop and noop_pending else status
+        for _log in logs:
+            if _log['tags'] == 'err':
+                self.status = 'error'
+            if _log['tags'] == 'warning' and self.status not in ['error', 'failed']:
+                self.status = 'warning'
         self.metrics = metrics
         self.logs = logs
         self.code_id = code_id
```

**Comment by Rewerson** [comment]
@b4ldr so could your solution be merged into master?

**Comment by b4ldr** [comment]
@Rewerson i'd prefer someone more familiar with this code to make that call, although im not sure who that is.  perhaps @bastelfreak ?

**Comment by marszip** [comment]
We are experiencing the same issues, is it possible to look into this?

**Comment by gdubicki** [comment]
The change from #170 is a step in the right direction for pypuppetdb ...but it won't be enough to fix the Puppetboard issue. 

In Puppetboard the list of nodes with their statuses would have to make an extra query for each node to get its latest report to determine if the status wasn't in facts "error". That would most probably cause a big performance drop.

It would make the most sense to make this extra call only if there are some indicators for a given node that it's worth doing it. But what are they? We only have the fields of the [Nodes API endpoint](https://puppet.com/docs/puppetdb/latest/api/query/v4/nodes.html) available...
