### ISSUE TITLE
RPM Build Fails due to missing requirements-test.txt

### ISSUE THREAD

**Issue by kevinbarbour** [voxpupuli/pypuppetdb#174]
The setup.cfg contains configuration for building an rpm via `setup.py bdist_rpm`. This fails due to the setup script requiring `requirements-test.txt` but `MANIFEST.in` and therefore the generated `pypuppetdb.egg-info/SOURCES.txt` do not include that file.

```
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd pypuppetdb-2.0.0rc0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.piylCJ
+ umask 022
+ cd /home/vagrant/pypuppetdb/build/bdist.linux-x86_64/rpm/BUILD
+ cd pypuppetdb-2.0.0rc0
+ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    with open('requirements-test.txt', 'r') as f:
IOError: [Errno 2] No such file or directory: 'requirements-test.txt'
error: Bad exit status from /var/tmp/rpm-tmp.piylCJ (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.piylCJ (%build)
error: command 'rpmbuild' failed with exit status 1
```

**Comment by bastelfreak** [comment]
Hi @barbourkd, thanks for raising this issue. Are you able to provide a PR for this?

**Comment by barbourkd** [comment]
Yeah, happy to. I can put one in tomorrow. 

Not sure what the preferred fix is though. I got it working for my purposes by just including the file in the manifest, but would it be preferable to change the setup scripts so that the requirements-test.txt isn’t necessary for the RPM packaging?

**Comment by gdubicki** [comment]
Hi @kevinbarbour !

We have recently deprecated and removed the code for building RPMs as it was outdated and we had no official RPMs built with the library anyway. Therefore I am closing this issue.

But if you can provide a PR that restores the config for building RPMs properly then we will be happy to review and merge. :)
