### ISSUE TITLE
Use PQL when searching for nodes with certain facts

### ISSUE THREAD

**Issue by azbarcea** [voxpupuli/pypuppetdb#180]
When having a large infrastructure, iterating through all nodes is not efficient.

Wondering if a translation cannot be done to use PQL so that the results are limited to only the list of nodes.

Uses: _expose PQL API_: #167

**Comment by azbarcea** [comment]
will work on a PR !

**Comment by gdubicki** [comment]
Thanks for reporting this @azbarcea !

If you don't have the time to create the PR, can you share you idea what exactly would you improve - which queries, which views? Maybe someone else will implement it based on your suggestions. :)

**Comment by gdubicki** [comment]
`pql()` method has been added in v2.4.0.rc1. Please feel free to test it, @azbarcea !

**Comment by gdubicki** [comment]
This should be done with the release of final v2.4.0.
