### ISSUE TITLE
How to use node.facts

### ISSUE THREAD

**Issue by rushi47** [voxpupuli/pypuppetdb#183]
Am trying to use node.facts, my assumption was it will return all the facts attached to node but it just gives object of puppet type which is not iterable. Also i tried doing dir(node.facts) but i was unable to find anything helpful. Whats the proper way to get all facts attached to Node ?

Please let me know if some more info is needed

Thanks a lot in advance :)

**Comment by b4ldr** [comment]
@rushi47 facts is a method i.e. facts().  the following works

```python
from pypuppetdb import connect
db = connect()
nodes = db.nodes()
for node in nodes:
    print(node)
    for fact in node.facts():
        print(fact)
```

**Comment by rushi47** [comment]
Thanks a lot @b4ldr :)
