### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [voxpupuli/pypuppetdb#227]
Could you please consider to utilize unittest.mock instead of mock, as a fallback at least?

**Comment by gdubicki** [comment]
Hi @pgajdos! Why would we want that?

**Comment by pgajdos** [comment]
I think it could be considered nice to drop dependencies which are not required.

**Comment by pgajdos** [comment]
Background: https://trello.com/c/S6eADbii/64-remove-python-mock

**Comment by gdubicki** [comment]
Oh, then sure. Can you create PR for this as you already investigated the subject?

**Comment by pgajdos** [comment]
Done: #228

**Comment by gdubicki** [comment]
Thanks again @pgajdos! Released in [v2.5.2](https://github.com/voxpupuli/pypuppetdb/releases/tag/2.5.2).
