### ISSUE TITLE
after upgrade to 0.2.2 error in puppetboard version 0.1.3

### ISSUE THREAD

**Issue by betorvs** [voxpupuli/pypuppetdb#84]
Hi all,

I create this ticket https://github.com/voxpupuli/puppetboard/issues/238, and after run the downgrade (pip install -I pypuppetdb==0.2.1), the puppetboard start show facts.

Any ideas?

This is log in puppetboard:
[Wed May 11 18:08:17.643928 2016] [:error] [pid 29196:tid 139886690535168] ERROR:puppetboard.app:Exception on /fact/architecture [GET]
[Wed May 11 18:08:17.643963 2016] [:error] [pid 29196:tid 139886690535168] Traceback (most recent call last):
[Wed May 11 18:08:17.643972 2016] [:error] [pid 29196:tid 139886690535168] File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
[Wed May 11 18:08:17.643979 2016] [:error] [pid 29196:tid 139886690535168] response = self.full_dispatch_request()
[Wed May 11 18:08:17.643985 2016] [:error] [pid 29196:tid 139886690535168] File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
[Wed May 11 18:08:17.643991 2016] [:error] [pid 29196:tid 139886690535168] rv = self.handle_user_exception(e)
[Wed May 11 18:08:17.643997 2016] [:error] [pid 29196:tid 139886690535168] File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
[Wed May 11 18:08:17.644003 2016] [:error] [pid 29196:tid 139886690535168] reraise(exc_type, exc_value, tb)
[Wed May 11 18:08:17.644009 2016] [:error] [pid 29196:tid 139886690535168] File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
[Wed May 11 18:08:17.644015 2016] [:error] [pid 29196:tid 139886690535168] rv = self.dispatch_request()
[Wed May 11 18:08:17.644021 2016] [:error] [pid 29196:tid 139886690535168] File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
[Wed May 11 18:08:17.644049 2016] [:error] [pid 29196:tid 139886690535168] return self.view_functionsrule.endpoint
[Wed May 11 18:08:17.644062 2016] [:error] [pid 29196:tid 139886690535168] File "/usr/local/lib/python2.7/dist-packages/puppetboard/app.py", line 689, in fact
[Wed May 11 18:08:17.644068 2016] [:error] [pid 29196:tid 139886690535168] name=fact, query=query))]
[Wed May 11 18:08:17.644073 2016] [:error] [pid 29196:tid 139886690535168] File "/usr/local/lib/python2.7/dist-packages/puppetboard/utils.py", line 42, in yield_or_stop
[Wed May 11 18:08:17.644079 2016] [:error] [pid 29196:tid 139886690535168] yield next(generator)
[Wed May 11 18:08:17.644083 2016] [:error] [pid 29196:tid 139886690535168] File "/usr/local/lib/python2.7/dist-packages/pypuppetdb/api/init.py", line 534, in facts
[Wed May 11 18:08:17.644089 2016] [:error] [pid 29196:tid 139886690535168] facts = self._query('facts', query=query, **kwargs)
[Wed May 11 18:08:17.644098 2016] [:error] [pid 29196:tid 139886690535168] TypeError: _query() got multiple values for keyword argument 'query'
[Wed May 11 18:08:17.644241 2016] [:error] [pid 29196:tid 139886690535168] DEBUG:pypuppetdb.api:_query called with endpoint: environments, path: None, query: None, limit: None, offset: None, summarize_by None, count_by None, count_filter: None

**Comment by corey-hammerton** [comment]
This bug was caused by https://github.com/voxpupuli/pypuppetdb/pull/68

**Comment by bbraunstein** [comment]
Also receiving similar errors.

Python2.6
PyPuppetDB 0.2.2
PuppetBoard 0.1.3
PuppetDB 4.0.2

[Thu May 12 09:37:52 2016] [error] ERROR:puppetboard.app:Exception on /node/node.example.com [GET]
[Thu May 12 09:37:52 2016] [error] Traceback (most recent call last):
[Thu May 12 09:37:52 2016] [error]   File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
[Thu May 12 09:37:52 2016] [error]     response = self.full_dispatch_request()
[Thu May 12 09:37:52 2016] [error]   File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Thu May 12 09:37:52 2016] [error]     rv = self.handle_user_exception(e)
[Thu May 12 09:37:52 2016] [error]   File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
[Thu May 12 09:37:52 2016] [error]     reraise(exc_type, exc_value, tb)
[Thu May 12 09:37:52 2016] [error]   File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Thu May 12 09:37:52 2016] [error]     rv = self.dispatch_request()
[Thu May 12 09:37:52 2016] [error]   File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
[Thu May 12 09:37:52 2016] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu May 12 09:37:52 2016] [error]   File "/usr/lib/python2.6/site-packages/puppetboard/app.py", line 369, in node
[Thu May 12 09:37:52 2016] [error]     for report in reports_events:
[Thu May 12 09:37:52 2016] [error]   File "/usr/lib/python2.6/site-packages/pypuppetdb/api/__init__.py", line 815, in reports
[Thu May 12 09:37:52 2016] [error]     events=report['resource_events']['data']
[Thu May 12 09:37:52 2016] [error]   File "/usr/lib/python2.6/site-packages/pypuppetdb/types.py", line 199, in __init__
[Thu May 12 09:37:52 2016] [error]     for event in events:
[Thu May 12 09:37:52 2016] [error] TypeError: 'NoneType' object is not iterable

**Comment by corey-hammerton** [comment]
@bbraunstein Please downgrade pypuppetdb to 0.2.1

**Comment by bbraunstein** [comment]
@corey-hammerton Does pypuppetdb 0.2.1 support PuppetDB >4.0.0 ? Or is the .1 just a minor version?

**Comment by corey-hammerton** [comment]
pypuppetdb 0.2.1 does support PuppetDB 4.0 with only minor differences. Those additions were added in https://github.com/voxpupuli/pypuppetdb/commit/3449fdafe1fb39088a28cb647d216061d3ce1fd9.

I will merge all the PRs in the 0.2.3 milestone and release this as soon as I can.

**Comment by corey-hammerton** [comment]
This bug is related to https://github.com/voxpupuli/pypuppetdb/issues/67

**Comment by jrdiniz** [comment]
After upgrade puppetboard stop to work

Traceback (most recent call last):
[Tue Jun 21 18:07:42 2016] [error]    File "/usr/lib/python2.6/site-packages/flask/app.py", line 1836, in __call__
[Tue Jun 21 18:07:42 2016] [error]      return self.wsgi_app(environ, start_response)
[Tue Jun 21 18:07:42 2016] [error]    File "/usr/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
[Tue Jun 21 18:07:42 2016] [error]     response = self.make_response(self.handle_exception(e))
[Tue Jun 21 18:07:42 2016] [error]    File "/usr/lib/python2.6/site-packages/flask/app.py", line 1410, in handle_exception
[Tue Jun 21 18:07:42 2016] [error]      return handler(e)
[Tue Jun 21 18:07:42 2016] [error]   File "/usr/lib/python2.6/site-packages/puppetboard/app.py", line 122, in server_error
[Tue Jun 21 18:07:42 2016] [error]      envs = environments()
[Tue Jun 21 18:07:42 2016] [error]    File "/usr/lib/python2.6/site-packages/puppetboard/app.py", line 71, in environments
[Tue Jun 21 18:07:42 2016] [error]      envs = get_or_abort(puppetdb.environments)
[Tue Jun 21 18:07:42 2016] [error]    File "/usr/lib/python2.6/site-packages/puppetboard/utils.py", line 26, in get_or_abort
[Tue Jun 21 18:07:42 2016] [error]      abort(e.response.status_code)
[Tue Jun 21 18:07:42 2016] [error]    File "/usr/lib/python2.6/site-packages/werkzeug/exceptions.py", line 576, in __call__
[Tue Jun 21 18:07:42 2016] [error]     raise self.mapping[code](*args, **kwargs)
[Tue Jun 21 18:07:42 2016] [error]  NotFound: 404: Not Found

Packages Installed:

Flask==0.10.1
Flask-WTF==0.9.4
Jinja2==2.7.2
MarkupSafe==0.19
WTForms==1.0.5
Werkzeug==0.9.4
click==6.6
iniparse==0.3.1
itsdangerous==0.23
ordereddict==1.1
puppetboard==0.1.3
pycurl==7.19.0
pygpgme==0.1
pypuppetdb==0.3.1
requests==2.6.0
urlgrabber==3.9.1
yum-metadata-parser==1.1.2
yum-presto==0.4.4

**Comment by corey-hammerton** [comment]
@jrdiniz What version of PuppetDB are you running?

Puppetboard 0.1.x only supports PuppetDB 3.x
