### ISSUE TITLE
Query builder changes make all nodes "unresponsive"

### ISSUE THREAD

**Issue by bootc** [voxpupuli/pypuppetdb#95]
Somehow, 564f7da1742c66123eaa44a18235c8402a1f7fb8 ("Query builder (#92)") causes PuppetBoard to show all nodes as unresponsive. Reverting this single commit fixes the issue.

All the nodes show the correct time for the last report, but the node status is always "unresponsive" regardless of the checkin time.

**Comment by corey-hammerton** [comment]
This is more likely caused by some of the code cleaned up in https://github.com/voxpupuli/pypuppetdb/pull/89

**Comment by bootc** [comment]
Thanks Corey, I can confirm that fixes the bug.
