### ISSUE TITLE
latest_report_noop not fully removed

### ISSUE THREAD

**Issue by bootc** [voxpupuli/pypuppetdb#96]
I noticed while investigating #95 that b768e129f1fc8de6557014e1768893ccfb948bd8 ("pypuppetdb/types.py: Removing the latest_report_noop variable from th…") is incomplete: [pypuppetdb/api.py line 410](https://github.com/voxpupuli/pypuppetdb/blob/b768e129f1fc8de6557014e1768893ccfb948bd8/pypuppetdb/api.py#L410) still refers to the `latest_report_noop` variable.

I originally thought this might be the cause of #95 but reverting b768e129f1fc8de6557014e1768893ccfb948bd8 does not correct the behaviour.

**Comment by corey-hammerton** [comment]
latest_report_noop was only removed from the Node type. It is only used now to determine if the latest report was run with `--noop`
